-- Triggers PET_CARE_LOG
-- 1
CREATE OR REPLACE TRIGGER FIRST_TRIGGER
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    :NEW.CREATED_BY_USER := USER;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Error in FIRST_TRIGGER: ' || SQLERRM
        );
END;

-- 2
CREATE OR REPLACE TRIGGER SECOND_TRIGGER
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF:NEW.CREATED_BY_USER != USER THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Error in SECOND_TRIGGER: ' || SQLERRM
        );
    END IF;
END;

-- 3
CREATE OR REPLACE TRIGGER THIRD_TRIGGER
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF:USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Error in THIRD_TRIGGER, YOU ARE NOT JOEMANAGER: ' || SQLERRM
        );
    END IF;
END;
